// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors
//
// GENERATED by vortex-cuda/kernels/gen_packed_grid.py — do not edit.
// Coarsening rung K=7 at 256 threads/block, minBlocks=6.
#define TOKENS_PER_THREAD    7u
#define ONPAIR_BLOCK_THREADS 256u
#define ONPAIR_MIN_BLOCKS    6u
#define ONPAIR_KERNEL_NAME   onpair_dg_k7_t256_b6
#include "onpair_decompress_tpt.cuh"
