// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors
//
// GENERATED by vortex-cuda/kernels/gen_packed_grid.py — do not edit.
// High-read-cap arm: K=4, 256 threads/block, minBlocks=8, C=3 hoisted rounds.
#define TOKENS_PER_THREAD      4u
#define ONPAIR_BLOCK_THREADS   256u
#define ONPAIR_MIN_BLOCKS      8u
#define ONPAIR_HIGH_READ_CAP   3u
#define ONPAIR_KERNEL_NAME     onpair_dc_k4_t256_b8_c3
#include "onpair_decompress_tpt.cuh"
