// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors
//
// GENERATED by vortex-cuda/kernels/gen_packed_grid.py — do not edit.
// Held-high arm: K=7, 256 threads/block, minBlocks=6, H=2 held rounds.
#define TOKENS_PER_THREAD      7u
#define ONPAIR_BLOCK_THREADS   256u
#define ONPAIR_MIN_BLOCKS      6u
#define ONPAIR_HELD_HIGH       2u
#define ONPAIR_KERNEL_NAME     onpair_dh_k7_t256_b6_h2
#include "onpair_decompress_tpt.cuh"
