// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors
//
// GENERATED by vortex-cuda/kernels/gen_packed_grid.py — do not edit.
// High-read-cap arm: K=8, 128 threads/block, minBlocks=8, C=4 hoisted rounds.
#define TOKENS_PER_THREAD      8u
#define ONPAIR_BLOCK_THREADS   128u
#define ONPAIR_MIN_BLOCKS      8u
#define ONPAIR_HIGH_READ_CAP   4u
#define ONPAIR_KERNEL_NAME     onpair_dc_k8_t128_b8_c4
#include "onpair_decompress_tpt.cuh"
