// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors
//
// GENERATED by vortex-cuda/kernels/gen_packed_grid.py — do not edit.
// Held-high arm: K=8, 128 threads/block, minBlocks=4, H=2 held rounds.
#define TOKENS_PER_THREAD      8u
#define ONPAIR_BLOCK_THREADS   128u
#define ONPAIR_MIN_BLOCKS      4u
#define ONPAIR_HELD_HIGH       2u
#define ONPAIR_KERNEL_NAME     onpair_dh_k8_t128_b4_h2
#include "onpair_decompress_tpt.cuh"
