// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors
//
// GENERATED by vortex-cuda/kernels/gen_packed_grid.py — do not edit.
// W=16 arm: K=8, 128 threads/block, minBlocks=6. One padded stride-16 read per token,
// so no high plane, no request queue and no hoist.
#define TOKENS_PER_THREAD      8u
#define ONPAIR_BLOCK_THREADS   128u
#define ONPAIR_MIN_BLOCKS      6u
#define ONPAIR_LOW_PLANE_BYTES 16u
#define ONPAIR_KERNEL_NAME     onpair_dw_k8_t128_b6
#include "onpair_decompress_tpt.cuh"
