// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors
//
// GENERATED by vortex-cuda/kernels/gen_packed_grid.py — do not edit.
// Coarsening rung K=5 at 128 threads/block, minBlocks=1.
#define TOKENS_PER_THREAD    5u
#define ONPAIR_BLOCK_THREADS 128u
#define ONPAIR_MIN_BLOCKS    1u
#define ONPAIR_KERNEL_NAME   onpair_dg_k5_t128_b1
#include "onpair_decompress_tpt.cuh"
