// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors
//
// GENERATED by vortex-cuda/kernels/gen_packed_grid.py — do not edit.
// Held-high arm: K=4, 256 threads/block, minBlocks=8, H=3 held rounds.
#define TOKENS_PER_THREAD      4u
#define ONPAIR_BLOCK_THREADS   256u
#define ONPAIR_MIN_BLOCKS      8u
#define ONPAIR_HELD_HIGH       3u
#define ONPAIR_KERNEL_NAME     onpair_dh_k4_t256_b8_h3
#include "onpair_decompress_tpt.cuh"
