// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors
//
// GENERATED by vortex-cuda/kernels/gen_packed_grid.py — do not edit.
// High-read-cap arm: K=6, 128 threads/block, minBlocks=2, C=2 hoisted rounds.
#define TOKENS_PER_THREAD      6u
#define ONPAIR_BLOCK_THREADS   128u
#define ONPAIR_MIN_BLOCKS      2u
#define ONPAIR_HIGH_READ_CAP   2u
#define ONPAIR_KERNEL_NAME     onpair_dc_k6_t128_b2_c2
#include "onpair_decompress_tpt.cuh"
