// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors
//
// GENERATED by vortex-cuda/kernels/gen_packed_grid.py — do not edit.
// Held-high arm: K=5, 256 threads/block, minBlocks=6, H=4 held rounds.
#define TOKENS_PER_THREAD      5u
#define ONPAIR_BLOCK_THREADS   256u
#define ONPAIR_MIN_BLOCKS      6u
#define ONPAIR_HELD_HIGH       4u
#define ONPAIR_KERNEL_NAME     onpair_dh_k5_t256_b6_h4
#include "onpair_decompress_tpt.cuh"
