// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors
//
// GENERATED by vortex-cuda/kernels/gen_packed_grid.py — do not edit.
// Held-high arm: K=8, 64 threads/block, minBlocks=6, H=3 held rounds.
#define TOKENS_PER_THREAD      8u
#define ONPAIR_BLOCK_THREADS   64u
#define ONPAIR_MIN_BLOCKS      6u
#define ONPAIR_HELD_HIGH       3u
#define ONPAIR_KERNEL_NAME     onpair_dh_k8_t64_b6_h3
#include "onpair_decompress_tpt.cuh"
