// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors
//
// GENERATED by vortex-cuda/kernels/gen_packed_grid.py — do not edit.
// Staging arm: K=8, 256 threads/block, minBlocks=8, S=14 staging bytes per token.
// Safe only where the column's largest batch fits; the host checks that against the offset
// sidecar and reports the kernel inapplicable otherwise.
#define TOKENS_PER_THREAD      8u
#define ONPAIR_BLOCK_THREADS   256u
#define ONPAIR_MIN_BLOCKS      8u
#define ONPAIR_STAGE_BYTES     14u
#define ONPAIR_KERNEL_NAME     onpair_ds_k8_t256_b8_s14
#include "onpair_decompress_tpt.cuh"
