// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors
//
// GENERATED by vortex-cuda/kernels/gen_packed_grid.py — do not edit.
// High-read-cap arm: K=4, 128 threads/block, minBlocks=4, C=4 hoisted rounds.
#define TOKENS_PER_THREAD      4u
#define ONPAIR_BLOCK_THREADS   128u
#define ONPAIR_MIN_BLOCKS      4u
#define ONPAIR_HIGH_READ_CAP   4u
#define ONPAIR_KERNEL_NAME     onpair_dc_k4_t128_b4_c4
#include "onpair_decompress_tpt.cuh"
