// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors
//
// GENERATED by vortex-cuda/kernels/gen_packed_grid.py — do not edit.
// Held-high arm: K=7, 64 threads/block, minBlocks=2, H=4 held rounds.
#define TOKENS_PER_THREAD      7u
#define ONPAIR_BLOCK_THREADS   64u
#define ONPAIR_MIN_BLOCKS      2u
#define ONPAIR_HELD_HIGH       4u
#define ONPAIR_KERNEL_NAME     onpair_dh_k7_t64_b2_h4
#include "onpair_decompress_tpt.cuh"
