// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors
//
// GENERATED by vortex-cuda/kernels/gen_packed_grid.py — do not edit.
// W=16 arm: K=5, 64 threads/block, minBlocks=4. One padded stride-16 read per token,
// so no high plane, no request queue and no hoist.
#define TOKENS_PER_THREAD      5u
#define ONPAIR_BLOCK_THREADS   64u
#define ONPAIR_MIN_BLOCKS      4u
#define ONPAIR_LOW_PLANE_BYTES 16u
#define ONPAIR_KERNEL_NAME     onpair_dw_k5_t64_b4
#include "onpair_decompress_tpt.cuh"
