// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors
//
// GENERATED by vortex-cuda/kernels/gen_packed_grid.py — do not edit.
// Coarsening rung K=8 at 64 threads/block, minBlocks=4.
#define TOKENS_PER_THREAD    8u
#define ONPAIR_BLOCK_THREADS 64u
#define ONPAIR_MIN_BLOCKS    4u
#define ONPAIR_KERNEL_NAME   onpair_dg_k8_t64_b4
#include "onpair_decompress_tpt.cuh"
