// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors
//
// GENERATED by vortex-cuda/kernels/gen_packed_grid.py — do not edit.
// Coarsening rung K=3 at 128 threads/block, minBlocks=2.
#define TOKENS_PER_THREAD    3u
#define ONPAIR_BLOCK_THREADS 128u
#define ONPAIR_MIN_BLOCKS    2u
#define ONPAIR_KERNEL_NAME   onpair_dg_k3_t128_b2
#include "onpair_decompress_tpt.cuh"
