// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors
//
// GENERATED by vortex-cuda/kernels/gen_packed_grid.py — do not edit.
// High-read-cap arm: K=8, 64 threads/block, minBlocks=2, C=4 hoisted rounds.
#define TOKENS_PER_THREAD      8u
#define ONPAIR_BLOCK_THREADS   64u
#define ONPAIR_MIN_BLOCKS      2u
#define ONPAIR_HIGH_READ_CAP   4u
#define ONPAIR_KERNEL_NAME     onpair_dc_k8_t64_b2_c4
#include "onpair_decompress_tpt.cuh"
