#!/usr/bin/env python3
"""Generate the packed decoder's (K, block threads, minBlocks) sweep kernels.

The launch configuration is a parameter of the coarsening study, not background. __launch_bounds__
is compile-time, so each point in the grid needs its own translation unit; there is no way to vary
it from the host. This emits those units and the matching KernelVariant registrations.

Regenerate with:

    python3 vortex-cuda/kernels/gen_packed_grid.py

Idempotent. Rewrites every generated .cu and the block delimited by the BEGIN/END markers in
vortex-bench/src/onpair_bench.rs.
"""
import pathlib
import re

K_VALUES = (1, 2, 3, 4, 5, 6, 7, 8)
# W=16 mirrors the W=8 grid exactly, so the width comparison is matched at every launch
# configuration rather than only at one. C is probed in the region the K sweep found
# interesting; C>1 is meaningless at W=16, where there is no high plane to hoist.
C_K = (4, 6, 8)
C_VALUES = (2, 3, 4)
C_THREADS = (64, 128, 256)
C_MIN_BLOCKS = (2, 4, 8)
# 256 is the ceiling: the kernel indexes its shared arrays by warp_id up to WARPS_PER_BLOCK_MAX,
# which is derived from the block size.
THREADS = (64, 128, 256)
# Sets the register ceiling at regs_per_sm/(threads*minBlocks). 1 leaves the compiler unconstrained.
MIN_BLOCKS = (1, 2, 4, 6, 8)

ROOT = pathlib.Path(__file__).resolve().parent
SRC = ROOT / "src"
BENCH = ROOT.parent.parent / "vortex-bench" / "src" / "onpair_bench.rs"

BEGIN = "    // BEGIN generated packed grid (gen_packed_grid.py) — do not edit by hand\n"
END = "    // END generated packed grid\n"

CU_W = """// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors
//
// GENERATED by vortex-cuda/kernels/gen_packed_grid.py — do not edit.
// W=16 arm: K={k}, {t} threads/block, minBlocks={b}. One padded stride-16 read per token,
// so no high plane, no request queue and no hoist.
#define TOKENS_PER_THREAD      {k}u
#define ONPAIR_BLOCK_THREADS   {t}u
#define ONPAIR_MIN_BLOCKS      {b}u
#define ONPAIR_LOW_PLANE_BYTES 16u
#define ONPAIR_KERNEL_NAME     {name}
#include "onpair_decompress_tpt.cuh"
"""

CU_C = """// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors
//
// GENERATED by vortex-cuda/kernels/gen_packed_grid.py — do not edit.
// High-read-cap arm: K={k}, {t} threads/block, minBlocks={b}, C={c} hoisted rounds.
#define TOKENS_PER_THREAD      {k}u
#define ONPAIR_BLOCK_THREADS   {t}u
#define ONPAIR_MIN_BLOCKS      {b}u
#define ONPAIR_HIGH_READ_CAP   {c}u
#define ONPAIR_KERNEL_NAME     {name}
#include "onpair_decompress_tpt.cuh"
"""

CU = """// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors
//
// GENERATED by vortex-cuda/kernels/gen_packed_grid.py — do not edit.
// Coarsening rung K={k} at {t} threads/block, minBlocks={b}.
#define TOKENS_PER_THREAD    {k}u
#define ONPAIR_BLOCK_THREADS {t}u
#define ONPAIR_MIN_BLOCKS    {b}u
#define ONPAIR_KERNEL_NAME   {name}
#include "onpair_decompress_tpt.cuh"
"""

VARIANT = """    KernelVariant {{
        name: "{name}",
        layout: KernelLayout::{layout},
        chunk_size: {chunk},
        block_warps: {warps},
    }},
"""


def name_for(k, t, b):
    return f"onpair_dg_k{k}_t{t}_b{b}"


def main():
    stale = sorted(SRC.glob("onpair_dg_k*.cu")) + sorted(SRC.glob("onpair_dw_k*.cu")) \
        + sorted(SRC.glob("onpair_dc_k*.cu"))
    for path in stale:
        path.unlink()

    variants = []
    written = 0
    for k in K_VALUES:
        for t in THREADS:
            for b in MIN_BLOCKS:
                name = name_for(k, t, b)
                (SRC / f"{name}.cu").write_text(CU.format(k=k, t=t, b=b, name=name))
                written += 1
                variants.append(VARIANT.format(name=name, chunk=32 * k, warps=t // 32,
                                               layout="PackedSplit8"))

    for k in K_VALUES:
        for t in THREADS:
            for b in MIN_BLOCKS:
                name = f"onpair_dw_k{k}_t{t}_b{b}"
                (SRC / f"{name}.cu").write_text(CU_W.format(k=k, t=t, b=b, name=name))
                written += 1
                variants.append(VARIANT.format(name=name, chunk=32 * k, warps=t // 32,
                                               layout="PackedWide16"))

    for k in C_K:
        for t in C_THREADS:
            for b in C_MIN_BLOCKS:
                for c in C_VALUES:
                    if c > k:
                        continue
                    name = f"onpair_dc_k{k}_t{t}_b{b}_c{c}"
                    (SRC / f"{name}.cu").write_text(CU_C.format(k=k, t=t, b=b, c=c, name=name))
                    written += 1
                    variants.append(VARIANT.format(name=name, chunk=32 * k, warps=t // 32,
                                                   layout="PackedSplit8"))

    text = BENCH.read_text()
    block = BEGIN + "".join(variants) + END
    if BEGIN in text:
        start = text.index(BEGIN)
        stop = text.index(END) + len(END)
        text = text[:start] + block + text[stop:]
    else:
        # Insert immediately before the array's closing bracket.
        anchor = text.index("const GPU_KERNELS")
        close = text.index("\n];\n", anchor) + 1
        text = text[:close] + block + text[close:]
    BENCH.write_text(text)

    print(f"removed {len(stale)} stale, wrote {written} kernels, {len(variants)} registrations")


if __name__ == "__main__":
    main()
