#!/usr/bin/env python3
"""Generate the packed decoder's (K, block threads, minBlocks) sweep kernels.

The launch configuration is a parameter of the coarsening study, not background. __launch_bounds__
is compile-time, so each point in the grid needs its own translation unit; there is no way to vary
it from the host. This emits those units and the matching KernelVariant registrations.

Regenerate with:

    python3 vortex-cuda/kernels/gen_packed_grid.py

Idempotent. Rewrites every generated .cu and the block delimited by the BEGIN/END markers in
vortex-bench/src/onpair_bench.rs.
"""
import pathlib
import re

K_VALUES = (1, 2, 3, 4, 5, 6, 7, 8)
# W=16 mirrors the W=8 grid exactly, so the width comparison is matched at every launch
# configuration rather than only at one. C is probed in the region the K sweep found
# interesting; C>1 is meaningless at W=16, where there is no high plane to hoist.
# H (held high rounds) only does anything once the queue is deeper than 32*(H-1), so it is
# instantiated across the whole K range rather than three rungs -- the previous grid omitted
# K=1,2,3,5,7 and B=1,6 while the job claimed H was swept over the grid. H=1 is the baseline
# arm, so only H>=2 needs its own kernel.
H_MAX = 4
# The h=0 no-hoist control is emitted only where fig:hoist reads it (see the loop below).
H0_THREADS = (256,)
H0_MIN_BLOCKS = (1, 4, 8)
H_THREADS = (64, 128, 256)
# FULL PARITY WITH THE MAIN GRID as of 2026-08-21. B=1 and B=6 were missing, and the reason to add
# them is that the __launch_bounds__ minimum does not itself dictate a register target there: at
# B in {2,4,8} ptxas must fit B blocks per SM, so raising H trades registers against residency by
# construction and H's latency-covering benefit cannot be read apart from the occupancy it costs.
#
# DO NOT restate this as "occupancy cannot move at B=1 and B=6". An earlier version of this comment
# did, claiming a 256-register ceiling at B=1 and a 5-block shared-memory pin at B=6; the committed
# H=1 probe (results/resource-probe-20260818, probe_k6_t256_b{1,6}) refutes both. At B=1 shared
# memory already caps residency at 4 blocks (3 on L40S), so the binding budget is 65536/(4*256) =
# 64 registers per thread and the kernel measures 56 to 64 -- at the boundary, not far below it.
# At B=6 residency is 5 blocks only on A100; it is 6 on H100 and B300 and 3 on L40S.
#
# So these rungs REMOVE a construction-forced confound; they do not establish that residency holds
# as H rises. The suite's H-aware resource-probe recipe now covers the same H=1..min(K,4) grid, but
# no such capture has landed yet. Until it does, a measured H effect here is the TOTAL effect of
# raising H, not an occupancy-isolated one, and must be reported as such.
H_MIN_BLOCKS = (1, 2, 4, 6, 8)
# S (staging bytes per token) only matters where it moves blocks*shared across a QUANTIZED
# carveout step, and in the realistic range -- mean token length is 7.8 to 11.8 B, so the
# largest batch needs roughly 10 to 12 -- there is about one step boundary near 12/13. Three
# values bracket it; sweeping 9..16 would mostly re-measure the same carveout.
S_VALUES = (10, 12, 14)
S_K = (4, 6, 8)
S_THREADS = (128, 256)
S_MIN_BLOCKS = (2, 4, 8)
# 256 is the ceiling: the kernel indexes its shared arrays by warp_id up to WARPS_PER_BLOCK_MAX,
# which is derived from the block size.
THREADS = (64, 128, 256)
# Sets the register ceiling at regs_per_sm/(threads*minBlocks). 1 leaves the compiler unconstrained.
MIN_BLOCKS = (1, 2, 4, 6, 8)

ROOT = pathlib.Path(__file__).resolve().parent
SRC = ROOT / "src"
BENCH = ROOT.parent.parent / "vortex-bench" / "src" / "onpair_bench.rs"

BEGIN = "    // BEGIN generated packed grid (gen_packed_grid.py) — do not edit by hand\n"
END = "    // END generated packed grid\n"

CU_W = """// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors
//
// GENERATED by vortex-cuda/kernels/gen_packed_grid.py — do not edit.
// W=16 arm: K={k}, {t} threads/block, minBlocks={b}. One padded stride-16 read per token,
// so no high plane, no request queue and no hoist.
#define TOKENS_PER_THREAD      {k}u
#define ONPAIR_BLOCK_THREADS   {t}u
#define ONPAIR_MIN_BLOCKS      {b}u
#define ONPAIR_LOW_PLANE_BYTES 16u
#define ONPAIR_KERNEL_NAME     {name}
#include "onpair_decompress_tpt.cuh"
"""

CU_S = """// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors
//
// GENERATED by vortex-cuda/kernels/gen_packed_grid.py — do not edit.
// Staging arm: K={k}, {t} threads/block, minBlocks={b}, S={s} staging bytes per token.
// Safe only where the column's largest batch fits; the host checks that against the offset
// sidecar and reports the kernel inapplicable otherwise.
#define TOKENS_PER_THREAD      {k}u
#define ONPAIR_BLOCK_THREADS   {t}u
#define ONPAIR_MIN_BLOCKS      {b}u
#define ONPAIR_STAGE_BYTES     {s}u
#define ONPAIR_KERNEL_NAME     {name}
#include "onpair_decompress_tpt.cuh"
"""

CU_H = """// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors
//
// GENERATED by vortex-cuda/kernels/gen_packed_grid.py — do not edit.
// Held-high arm: K={k}, {t} threads/block, minBlocks={b}, H={h} held rounds.
#define TOKENS_PER_THREAD      {k}u
#define ONPAIR_BLOCK_THREADS   {t}u
#define ONPAIR_MIN_BLOCKS      {b}u
#define ONPAIR_HELD_HIGH       {h}u
#define ONPAIR_KERNEL_NAME     {name}
#include "onpair_decompress_tpt.cuh"
"""

CU = """// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors
//
// GENERATED by vortex-cuda/kernels/gen_packed_grid.py — do not edit.
// Coarsening rung K={k} at {t} threads/block, minBlocks={b}.
#define TOKENS_PER_THREAD    {k}u
#define ONPAIR_BLOCK_THREADS {t}u
#define ONPAIR_MIN_BLOCKS    {b}u
#define ONPAIR_KERNEL_NAME   {name}
#include "onpair_decompress_tpt.cuh"
"""

VARIANT = """    KernelVariant {{
        name: "{name}",
        layout: KernelLayout::{layout},
        chunk_size: {chunk},
        block_warps: {warps},
        stage_bytes: {stage},
        role: KernelRole::Experimental,
    }},
"""


def name_for(k, t, b):
    return f"onpair_dg_k{k}_t{t}_b{b}"


def main():
    stale = sorted(SRC.glob("onpair_dg_k*.cu")) + sorted(SRC.glob("onpair_dw_k*.cu")) \
        + sorted(SRC.glob("onpair_dc_k*.cu")) + sorted(SRC.glob("onpair_dh_k*.cu")) + sorted(SRC.glob("onpair_ds_k*.cu"))
    for path in stale:
        path.unlink()

    variants = []
    written = 0
    for k in K_VALUES:
        for t in THREADS:
            for b in MIN_BLOCKS:
                name = name_for(k, t, b)
                (SRC / f"{name}.cu").write_text(CU.format(k=k, t=t, b=b, name=name))
                written += 1
                variants.append(VARIANT.format(name=name, chunk=32 * k, warps=t // 32,
                                               layout="PackedSplit8", stage="None"))

    for k in K_VALUES:
        for t in THREADS:
            for b in MIN_BLOCKS:
                name = f"onpair_dw_k{k}_t{t}_b{b}"
                (SRC / f"{name}.cu").write_text(CU_W.format(k=k, t=t, b=b, name=name))
                written += 1
                variants.append(VARIANT.format(name=name, chunk=32 * k, warps=t // 32,
                                               layout="PackedWide16", stage="None"))

    for k in K_VALUES:
        for t in H_THREADS:
            for b in H_MIN_BLOCKS:
                # h=0 IS THE NO-HOIST CONTROL. H=1 is the shipped decoder and already hoists one
                # round, so without an h=0 arm every hoist measurement compares one amount of
                # hoisting against another and none of them isolates the hoist itself.
                #
                # SCOPED TO WHAT fig:hoist READS, deliberately. That figure is pinned to
                # loghub-windows/line at OnPair-12 on the b300, T=256, B in {1,4,8}, K=1..8 -- so
                # 24 kernels answer it. Emitting h=0 across the whole dh grid instead would add 120
                # and put roughly +20% on every full GRID pass forever, for coordinates no figure
                # reads. The arm is therefore non-rectangular against h>=2 on purpose; widen
                # H0_THREADS/H0_MIN_BLOCKS if a later question needs it.
                #
                # These coordinates exist in the dg family too (H_THREADS/H_MIN_BLOCKS are the same
                # tuples as THREADS/MIN_BLOCKS), which is what makes h0-against-dg a like-for-like
                # delta. Comparing across mismatched coordinates is how the S axis once produced a
                # spurious -22.8%.
                hs = list(range(2, min(k, H_MAX) + 1))
                if t in H0_THREADS and b in H0_MIN_BLOCKS:
                    hs = [0] + hs
                for h in hs:
                    name = f"onpair_dh_k{k}_t{t}_b{b}_h{h}"
                    (SRC / f"{name}.cu").write_text(CU_H.format(k=k, t=t, b=b, h=h, name=name))
                    written += 1
                    variants.append(VARIANT.format(name=name, chunk=32 * k, warps=t // 32,
                                                   layout="PackedSplit8", stage="None"))

    for k in S_K:
        for t in S_THREADS:
            for b in S_MIN_BLOCKS:
                for sb in S_VALUES:
                    name = f"onpair_ds_k{k}_t{t}_b{b}_s{sb}"
                    (SRC / f"{name}.cu").write_text(CU_S.format(k=k, t=t, b=b, s=sb, name=name))
                    written += 1
                    variants.append(VARIANT.format(name=name, chunk=32 * k, warps=t // 32,
                                                   layout="PackedSplit8", stage=f"Some({sb})"))

    text = BENCH.read_text()
    block = BEGIN + "".join(variants) + END
    if BEGIN in text:
        start = text.index(BEGIN)
        stop = text.index(END) + len(END)
        text = text[:start] + block + text[stop:]
    else:
        # Insert immediately before the array's closing bracket.
        anchor = text.index("const GPU_KERNELS")
        close = text.index("\n];\n", anchor) + 1
        text = text[:close] + block + text[close:]
    BENCH.write_text(text)

    print(f"removed {len(stale)} stale, wrote {written} kernels, {len(variants)} registrations")


if __name__ == "__main__":
    main()
