#!/usr/bin/env python3
"""Generate the packed decoder's (K, block threads, minBlocks) sweep kernels.

The launch configuration is a parameter of the coarsening study, not background. __launch_bounds__
is compile-time, so each point in the grid needs its own translation unit; there is no way to vary
it from the host. This emits those units and the matching KernelVariant registrations.

Regenerate with:

    python3 vortex-cuda/kernels/gen_packed_grid.py

Idempotent. Rewrites every generated .cu and the block delimited by the BEGIN/END markers in
vortex-bench/src/onpair_bench.rs.
"""
import pathlib
import re

K_VALUES = (1, 2, 3, 4, 5, 6, 7, 8)
# 256 is the ceiling: the kernel indexes its shared arrays by warp_id up to WARPS_PER_BLOCK_MAX,
# which is derived from the block size.
THREADS = (64, 128, 256)
# Sets the register ceiling at regs_per_sm/(threads*minBlocks). 1 leaves the compiler unconstrained.
MIN_BLOCKS = (1, 2, 4, 6, 8)

ROOT = pathlib.Path(__file__).resolve().parent
SRC = ROOT / "src"
BENCH = ROOT.parent.parent / "vortex-bench" / "src" / "onpair_bench.rs"

BEGIN = "    // BEGIN generated packed grid (gen_packed_grid.py) — do not edit by hand\n"
END = "    // END generated packed grid\n"

CU = """// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors
//
// GENERATED by vortex-cuda/kernels/gen_packed_grid.py — do not edit.
// Coarsening rung K={k} at {t} threads/block, minBlocks={b}.
#define TOKENS_PER_THREAD    {k}u
#define ONPAIR_BLOCK_THREADS {t}u
#define ONPAIR_MIN_BLOCKS    {b}u
#define ONPAIR_KERNEL_NAME   {name}
#include "onpair_decompress_tpt.cuh"
"""

VARIANT = """    KernelVariant {{
        name: "{name}",
        layout: KernelLayout::PackedSplit8,
        chunk_size: {chunk},
        block_warps: {warps},
    }},
"""


def name_for(k, t, b):
    return f"onpair_dg_k{k}_t{t}_b{b}"


def main():
    stale = sorted(SRC.glob("onpair_dg_k*.cu"))
    for path in stale:
        path.unlink()

    variants = []
    written = 0
    for k in K_VALUES:
        for t in THREADS:
            for b in MIN_BLOCKS:
                name = name_for(k, t, b)
                (SRC / f"{name}.cu").write_text(CU.format(k=k, t=t, b=b, name=name))
                written += 1
                variants.append(VARIANT.format(name=name, chunk=32 * k, warps=t // 32))

    text = BENCH.read_text()
    block = BEGIN + "".join(variants) + END
    if BEGIN in text:
        start = text.index(BEGIN)
        stop = text.index(END) + len(END)
        text = text[:start] + block + text[stop:]
    else:
        # Insert immediately before the array's closing bracket.
        anchor = text.index("const GPU_KERNELS")
        close = text.index("\n];\n", anchor) + 1
        text = text[:close] + block + text[close:]
    BENCH.write_text(text)

    print(f"removed {len(stale)} stale, wrote {written} kernels, {len(variants)} registrations")


if __name__ == "__main__":
    main()
